### PR TITLE
chore: Adds dependabot support for automated dependency management

### PR DESCRIPTION
**Pull request by gruyaume**
## Description

This PR adds dependabot support for automating dependency management, just like it is done in other SD-Core repos like the [AMF](https://github.com/omec-project/amf) and [NRF](https://github.com/omec-project/nrf). Dependabot will automatically create pull requests, all we have to do is review and merge those.

## Rationale

Managing dependencies is critical for stability and security purposes and it's very difficult to stay up to date on a best effort basis.

### CODE REVIEW

**Comment by gab-arrobo** [comment]
test this please

**Comment by gab-arrobo** [comment]
retest this please

**Comment by gab-arrobo** [comment]
retest this please

**Comment by gab-arrobo** [comment]
> @gab-arrobo @thakurajayL Can this PR receive some reviews? This project's FOSSA and license verification seem to systematically fail.

@gruyaume, this is another request I sent to @dafATonf last week because the FOSSA and Licenses verification fail due to permissions issue in Jenkins. This same issue is happening in the [metricfunc repo](https://github.com/omec-project/metricfunc/pull/18). As soon this issue gets resolved, approving and merging your PR is pretty quick.

**Comment by gruyaume** [comment]
> > @gab-arrobo @thakurajayL Can this PR receive some reviews? This project's FOSSA and license verification seem to systematically fail.
> 
> @gruyaume, this is another request I sent to @dafATonf last week because the FOSSA and Licenses verification fail due to permissions issue in Jenkins. This same issue is happening in the [metricfunc repo](https://github.com/omec-project/metricfunc/pull/18). As soon this issue gets resolved, approving and merging your PR is pretty quick.

@gab-arrobo @dafATonf , Can you please fix the issue with the FOSSA verification? This is blocking all changes to this repo and effectively making it stale.

**Comment by gab-arrobo** [comment]
ok to test

**Pull request merged**
